routes/web.php
  Route::get('/suratijinobservasikelas/{id_surat}-{unique_key}', ['as' => 'SuratIjinObservasiKelas', 'uses' => 'Validasi\ValidasiSuratMahasiswaController@ValidasiSuratIjinObservasiKelas']);
  Route::get('/suratketeranganlulusskripsi/{id_surat}-{unique_key}', ['as' => 'SuratKeteranganLulusSkripsi', 'uses' => 'Validasi\ValidasiSuratMahasiswaController@ValidasiSuratKeteranganLulusSkripsi']);
  Route::get('/suratugas/{id_surat}-{unique_key}', ['as' => 'SuratTugas', 'uses' => 'Validasi\ValidasiSuratMahasiswaController@ValidasiSuratTugas']);
  Route::get('/suratketeranganmasihkuliah/{id_surat}-{unique_key}', ['as' => 'SuratKeteranganMasihKuliah', 'uses' => 'Validasi\ValidasiSuratMahasiswaController@ValidasiSuratKeteranganMasihKuliah']);
  Route::get('/suratketeranganpernahkuliah/{id_surat}-{unique_key}', ['as' => 'SuratKeteranganPernahKuliah', 'uses' => 'Validasi\ValidasiSuratMahasiswaController@ValidasiSuratKeteranganPernahKuliah']);
  Route::get('/suratketeranganpenggantiijazah/{id_surat}-{unique_key}', ['as' => 'SuratKeteranganPenggantiIjazah', 'uses' => 'Validasi\ValidasiSuratMahasiswaController@ValidasiSuratKeteranganPenggantiIjazah']);
  Route::get('/suratpermohonanapenghargaan/{id_surat}-{unique_key}', ['as' => 'SuratPermohonanPenghargaan', 'uses' => 'Validasi\ValidasiSuratMahasiswaController@ValidasiSuratPermohonanPenghargaan']);
});

Route::prefix('admin')->name('admin.')->group(function () {
  Route::get('/detailadmin', ['as' => 'DetailAdmin', 'uses' => 'Admin\AdminController@DetailAdmin']);
  Route::get('/tambahadmin', ['as' => 'TambahAdmin', 'uses' => 'Admin\AdminController@TambahAdmin']);
  Route::post('/simpanadmin', ['as' => 'SimpanAdmin', 'uses' => 'Admin\AdminController@SimpanAdmin']);
  Route::get('/editadmin/{id_user}', ['as' => 'EditAdmin', 'uses' => 'Admin\AdminController@EditAdmin']);
  Route::post('/updateadmin/{id_user}', ['as' => 'UpdateAdmin', 'uses' => 'Admin\AdminController@UpdateAdmin']);
  Route::get('/ubahpassword', ['as' => 'UbahPassword', 'uses' => 'Admin\AdminController@UbahPassword']);
  Route::post('/updatepassword', ['as' => 'UpdatePassword', 'uses' => 'Admin\AdminController@UpdatePassword']);
  Route::get('/tampiladmin', ['as' => 'TampilAdmin', 'uses' => 'Admin\AdminController@TampilAdmin']);
  Route::get('/detailadmin/admincari', ['as' => 'AdminCari', 'uses' => 'Admin\AdminController@AdminCari']);
  Route::get('/adm/detailadm', ['as' => 'DetailAdm', 'uses' => 'Admin\AdmController@DetailAdm']);
  Route::get('/adm/tambahadm', ['as' => 'TambahAdm', 'uses' => 'Admin\AdmController@TambahAdm']);
  Route::post('/adm/simpanadm', ['as' => 'SimpanAdm', 'uses' => 'Admin\AdmController@SimpanAdm']);
  Route::get('/adm/editadm/{id_user}', ['as' => 'EditAdm', 'uses' => 'Admin\AdmController@EditAdm']);
  Route::post('/adm/updateadm/{id_user}', ['as' => 'UpdateAdm', 'uses' => 'Admin\AdmController@UpdateAdm']);
  Route::get('/adm/tampiladm/{id_user}', ['as' => 'TampilAdm', 'uses' => 'Admin\AdmController@TampilAdm']);
  Route::get('/adm/ubahpassword/{id_user}', ['as' => 'UbahPasswordAdm', 'uses' => 'Admin\AdmController@UbahPassword']);
  Route::post('/adm/updatepasswordadm/{id_user}', ['as' => 'UpdatePasswordAdm', 'uses' => 'Admin\AdmController@UpdatePassword']);
  Route::get('/admcari', ['as' => 'AdmCari', 'uses' => 'Admin\AdmController@AdmCari']);



  Route::get('/tampilsuratmhs', ['as' => 'TampilSuratMhs', 'uses' => 'Admin\AdminController@TampilSuratMhs']);
  Route::get('/editsuratmhs/{id_surat_mahasiswa}', ['as' => 'EditSuratMhs', 'uses' => 'Admin\AdminController@EditSuratMhs']);
  Route::post('/updatesuratmhs/{id_surat_mahasiswa}', ['as' => 'UpdateSuratMhs', 'uses' => 'Admin\AdminController@UpdateSuratMhs']);
  Route::get('/detailsuratmh/{id_surat_mahasiswa}', ['as' => 'DetailSuratMhs', 'uses' => 'Admin\AdminController@DetailSuratMhs']);
  Route::get('/tampilsuratmhs/suratmhscari', ['as' => 'SuratMhsCari', 'uses' => 'Admin\AdminController@SuratMhsCari']);

  Route::get('/mhs/detailmhs', ['as' => 'DetailMhs', 'uses' => 'Admin\MhsController@DetailMhs']);
  Route::get('/mhs/editmhs/{id_user}', ['as' => 'EditMhs', 'uses' => 'Admin\MhsController@EditMhs']);
  Route::post('/mhs/updatemhs/{id_user}', ['as' => 'UpdateMhs', 'uses' => 'Admin\MhsController@UpdateMhs']);
  Route::get('/mhs/tampilmhs/{id_user}', ['as' => 'TampilMhs', 'uses' => 'Admin\MhsController@TampilMhs']);
  Route::get('/mhs/ubahpasswordmhs/{id_user}', ['as' => 'UbahPasswordMhs', 'uses' => 'Admin\MhsController@UbahPassword']);
  Route::post('/mhs/updatepasswordmhs/{id_user}', ['as' => 'UpdatePasswordMhs', 'uses' => 'Admin\MhsController@UpdatePassword']);
  Route::get('/mhscari', ['as' => 'MhsCari', 'uses' => 'Admin\MhsController@MhsCari']);

  Route::get('/dosen/detaildosen', ['as' => 'DetailDosen', 'uses' => 'Admin\DosenController@DetailDosen']);
  Route::get('/dosen/tambahdosen', ['as' => 'TambahDosen', 'uses' => 'Admin\DosenController@TambahDosen']);
  Route::post('/dosen/simpandosen', ['as' => 'SimpanDosen', 'uses' => 'Admin\DosenController@SimpanDosen']);
  Route::get('/dosen/editdosen/{id_user}', ['as' => 'EditDosen', 'uses' => 'Admin\DosenController@EditDosen']);
  Route::post('/dosen/updatedosen/{id_user}', ['as' => 'UpdateDosen', 'uses' => 'Admin\DosenController@UpdateDosen']);
  Route::get('/dosen/tampildosen/{id_user}', ['as' => 'TampilDosen', 'uses' => 'Admin\DosenController@TampilDosen']);
  Route::get('/dosen/ubahpassworddosen/{id_user}', ['as' => 'UbahPasswordDosen', 'uses' => 'Admin\DosenController@UbahPassword']);
  Route::post('/dosen/updatepassworddosen/{id_user}', ['as' => 'UpdatePasswordDosen', 'uses' => 'Admin\DosenController@UpdatePassword']);
  Route::get('/dosencari', ['as' => 'DosenCari', 'uses' => 'Admin\DosenController@DosenCari']);

  Route::get('/jurusan',['as'=>'Jurusan','uses'=>'Admin\ProdiJurusanJabatanController@DaftarJurusan']);
  Route::get('/jurusan/ubah/{id_jurusan}',['as'=>'UbahJurusan','uses'=>'Admin\ProdiJurusanJabatanController@UbahJurusan']);
  Route::post('/jurusan/ubah/{id_jurusan}',['as'=>'SimpanUbahJurusan','uses'=>'Admin\ProdiJurusanJabatanController@SimpanUbahJurusan']);
  Route::get('/prodi',['as'=>'Prodi','uses'=>'Admin\ProdiJurusanJabatanController@DaftarProdi']);
  Route::get('/prodi/ubah/{id_prodi}',['as'=>'UbahProdi','uses'=>'Admin\ProdiJurusanJabatanController@UbahProdi']);
  Route::post('/prodi/ubah/{id_prodi}',['as'=>'SimpanUbahProdi','uses'=>'Admin\ProdiJurusanJabatanController@SimpanUbahProdi']);
  Route::get('/dekanwadek',['as'=>'DekanWadek','uses'=>'Admin\ProdiJurusanJabatanController@DaftarDekanWadek']);
  Route::get('/dekanwadek/ubah/{jabatan}',['as'=>'UbahDekanWadek','uses'=>'Admin\ProdiJurusanJabatanController@UbahDekanWadek']);
  Route::post('/dekanwadek/ubah/{jabatan}',['as'=>'SimpanUbahDekanWadek','uses'=>'Admin\ProdiJurusanJabatanController@SimpanUbahDekanWadek']);
  Route::get('/adminprodi',['as'=>'AdminProdi','uses'=>'Admin\ProdiJurusanJabatanController@AdminProdi']);
  Route::get('/adminprodi/tambah',['as'=>'TambahAdminProdi','uses'=>'Admin\ProdiJurusanJabatanController@TambahAdminProdi']);
  Route::post('/adminprodi/tambah',['as'=>'SimpanTambahAdminProdi','uses'=>'Admin\ProdiJurusanJabatanController@SimpanTambahAdminProdi']);
});



Route::get('/tampildekan', ['as' => 'TampilPenggunaDekan', 'uses' => 'PengaturanUserController@TampilPenggunaDekan']);
Route::get('/detaildekan', ['as' => 'DetailPenggunaDekan', 'uses' => 'PengaturanUserController@DetailPenggunaDekan']);
Route::get('/ubahdekan', ['as' => 'EditPenggunaDekan', 'uses' => 'PengaturanUserController@EditPenggunaDekan']);
Route::post('/updatedekan', ['as' => 'UpdatePenggunaDekan', 'uses' => 'PengaturanUserController@UpdatePenggunaDekan']);
Route::get('/ubahpassworddekan', ['as' => 'UbahPasswordPenggunaDekan', 'uses' => 'PengaturanUserController@UbahPasswordPenggunaDekan']);
Route::post('/updatepassworddekan', ['as' => 'UpdatePasswordPenggunaDekan', 'uses' => 'PengaturanUserController@UpdatePasswordPenggunaDekan']);

Route::get('/tampilwadek1', ['as' => 'TampilPenggunaWadek1', 'uses' => 'PengaturanUserController@TampilPenggunaWadek1']);
Route::get('/detailwadek1', ['as' => 'DetailPenggunaWadek1', 'uses' => 'PengaturanUserController@DetailPenggunaWadek1']);
Route::get('/ubahwadek1', ['as' => 'EditPenggunaWadek1', 'uses' => 'PengaturanUserController@EditPenggunaWadek1']);
Route::post('/updatewadek1', ['as' => 'UpdatePenggunaWadek1', 'uses' => 'PengaturanUserController@UpdatePenggunaWadek1']);
Route::get('/ubahpasswordwadek1', ['as' => 'UbahPasswordPenggunaWadek1', 'uses' => 'PengaturanUserController@UbahPasswordPenggunaWadek1']);
Route::post('/updatepasswordwadek1', ['as' => 'UpdatePasswordPenggunaWadek1', 'uses' => 'PengaturanUserController@UpdatePasswordPenggunaWadek1']);

Route::get('/detailwadek2', ['as' => 'DetailPenggunaWadek2', 'uses' => 'PengaturanUserController@DetailPenggunaWadek2']);
Route::get('/ubahwadek2', ['as' => 'EditPenggunaWadek2', 'uses' => 'PengaturanUserController@EditPenggunaWadek2']);
Route::post('/updatewadek2', ['as' => 'UpdatePenggunaWadek2', 'uses' => 'PengaturanUserController@UpdatePenggunaWadek2']);
Route::get('/ubahpasswordwadek2', ['as' => 'UbahPasswordPenggunaWadek2', 'uses' => 'PengaturanUserController@UbahPasswordPenggunaWadek2']);
Route::post('/updatepasswordwadek2', ['as' => 'UpdatePasswordPenggunaWadek2', 'uses' => 'PengaturanUserController@UpdatePasswordPenggunaWadek2']);

Route::get('/detailwadek3', ['as' => 'DetailPenggunaWadek3', 'uses' => 'PengaturanUserController@DetailPenggunaWadek3']);
Route::get('/ubahwadek3', ['as' => 'EditPenggunaWadek3', 'uses' => 'PengaturanUserController@EditPenggunaWadek3']);
Route::post('/updatewadek3', ['as' => 'UpdatePenggunaWadek3', 'uses' => 'PengaturanUserController@UpdatePenggunaWadek3']);
Route::get('/ubahpasswordwadek3', ['as' => 'UbahPasswordPenggunaWadek3', 'uses' => 'PengaturanUserController@UbahPasswordPenggunaWadek3']);

resources/views/admin/suratmhs/detailsuratmhs.blade.php
@extends('layout.main')
@section('title','Halaman Detail Surat Mahasiswa')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Detail Surat Mahasiswa</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->
  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card card-primary">
          <div class="card-header">
            Detail Surat Mahasiswa
          </div>
           <div class="card-body">
               @if (session('data_password'))
               <div class="alert alert-success alert-dismissible fade show" role="alert">
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
                 </button>
                 {{ session('data_password') }}
               </div>
                   
               @endif
               @if (session('data_diedit'))
               <div class="alert alert-success alert-dismissible fade show" role="alert">
                 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                   <span aria-hidden="true">&times;</span>
                 </button>
                 {{ session('data_diedit') }}
               </div>
                   
               @endif
               <table class="table table-striped">
                  
                   <tr>
                        <td width="100">Jenis Surat</td>
                        <td width="6">:</td>
                        <td width="">{{ $data->jenis_surat }}</td>
                    </tr>
                    <tr>
                        <td width="142">No Surat Awalan</td>
                        <td width="4">:</td>
                        <td width="274">{{ $data->no_surat_awalan }}</td>
                    </tr>
                    <tr>
                        <td width="142">No Surat Akhiran</td>
                        <td width="4">:</td>
                        <td width="274">{{ $data->no_surat_akhiran }}</td>
                    </tr>
                    <tr>
                        <td width="142">Nama Tabel</td>
                        <td width="4">:</td>
                        <td width="274">{{ $data->nama_tabel }}</td>
                    </tr>
                   
               </table>

               <div class="mt-3">
                <a href="{{ route('admin.EditSuratMhs',$data->id_surat_mahasiswa) }}" class="btn btn-primary">Edit</a>
                
               </div>
              
           </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
@endsection

resources/views/admin/suratmhs/editsuratmhs.blade.php
@extends('layout.main')
@section('title','Halaman Edit Surat Mhs')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Edit Surat Mahasiswa</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->
  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card card-primary">
          <div class="card-header">
            Form UbahSurat Mahasiswa
          </div>
          <div class="card-body">
                    
              <form action="{{ route('admin.UpdateSuratMhs', $data->id_surat_mahasiswa) }}" method="POST">
                {{ csrf_field() }}
                  <div class="mb-3 ">
                    <label for="jenis surat">Jenis Surat</label>
                    <input type="text" class="form-control @error('jenis_surat')  
                    is-invalid @enderror" name="jenis_surat"  placeholder="Jenis Surat" value="{{ old('jenis_surat', $data->jenis_surat )  }}" readonly>
                    @error('jenis_surat')
                    <div class="invalid-feedback">
                      {{ $message }}
                    </div>
                    @enderror
                    
                  </div>
                  <div class="mb-3">
                    <label for="no surat awalan">No Surat Awalan</label>
                    <input type="text" name="no_surat_awalan" placeholder="Nama Lengkap" class="form-control
                    @error('no_surat_awalan')   is-invalid @enderror" value={{ old('no_surat_awalan', $data->no_surat_awalan ) }} >
                    @error('no_surat_awalan')
                    <div class="invalid-feedback">
                      {{ $message }}
                    </div>
                    @enderror
                  </div>
                  <div class="mb-3">
                    <label for="telp">No Surat Akhiran</label>
                    <input type="text" name="no_surat_akhiran" placeholder="Nomor Telepon" class="form-control 
                    @error('no_surat_akhiran')   is-invalid @enderror" value="{{ old('no_surat_akhiran', $data->no_surat_akhiran ) }}" >
                    @error('no_surat_akhiran')
                    <div class="invalid-feedback">
                      {{ $message }}
                    </div>
                    @enderror
                  </div>
                  <div class="mb-3">
                    <label for="nama tabel">Nama Tabel</label>
                    <input type="text" name="nama_tabel" placeholder="Nomor Telepon" class="form-control 
                    @error('nama_tabel')   is-invalid @enderror" value="{{ old('nama_tabel', $data->nama_tabel ) }}" readonly >
                    @error('nama_tabel')
                    <div class="invalid-feedback">
                      {{ $message }}
                    </div>
                    @enderror
                  </div>
                  <button type="submit" class="btn btn-primary">Simpan</button>
                  <a href="{{ route('admin.TampilSuratMhs') }}" class="btn btn-secondary">Kembali</a>
              </form>
             
              
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
@endsection

resources/views/admin/suratmhs/tampilsuratmhs.blade.php
@extends('layout.main')
@section('title','Halaman Tampil Surat')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Surat Mahasiswa</h1>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->
  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card card-primary">
          <div class="card-header">
            Tampil Surat Mahasiswa
          </div>
          <div class="card-body">
            
            @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              {{ session('status') }}
            </div>
                
            @endif
            @if (session('data_diedit'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              {{ session('data_diedit') }}
            </div>
                
            @endif
            <div class="row">
              <div class="col-lg-9">
                {{-- <a href="{{ route('admin.TambahAdmin') }}" class="btn btn-success mb-3"><i class="fas fa-plus-circle"></i> Tambah Admin</a> --}}
              </div>
              <div class="col-lg-3" >
                <form class="form" method="get" action="{{ route('admin.SuratMhsCari') }}">
                  <div class="form-group">
                      <input type="text" name="cari" class="form-control w-75 d-inline" id="cari" placeholder="Masukkan Nama">
                      <button type="submit" class="btn btn-primary mb-1"><i class="fas fa-search"></i></button>
                  </div>
              </form>
              </div>
            </div>
          
            
             <table class="table table-bordered table-striped">
              <thead>
                <tr>
                <th>No.</th>
                <th>Jenis Surat</th>
                <th>No Surat Awalan</th>
                <th>No Surat Akhiran</th>
                <th>Aksi</th>
                </tr>
              </thead>
              @forelse ($data as $adm)
              <tr>
                <td>{{ $loop->iteration }}.</td>
                <td>{{ $adm->jenis_surat }}</td>
                <td>{{ $adm->no_surat_awalan }}</td>
                <td>{{ $adm->no_surat_akhiran }}</td>
                <td>
                  <a href="{{ route('admin.EditSuratMhs',$adm->id_surat_mahasiswa) }}" class="btn btn-info" title="Edit Data"><i class="fas fa-edit"></i></a>
                  <a href="{{ route('admin.DetailSuratMhs',$adm->id_surat_mahasiswa) }}" class="btn btn-danger" title="Lihat Data"><i class="fas fa-eye"></i></a>
               </a>
                </td>
              </tr>
              @empty
              <tr>
                <td colspan="5" class="text-center">Data Tidak Ada</td>
              </tr>
              @endforelse
            </table>
            <div class="mb-3"></div>
            {{ $data->links() }}
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>
</div>
@endsection